seo: 
  site_name: Tina's Amazing Blog
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text: 'rgb(60,60,65)'
  medium-text: 'rgb(90,90,95)'
  light-text: '#f7f5f3'
  featured-text: 'red'
  dark: 'rgb(60,60,65)'
  medium: '#ede8e4'
  light: '#f7f5f3'
  v-light: '#f9f9f9'
  featured: '#6495ed'
  accent: 'rgb(167, 74, 74)'
